apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: sudeepgowda55/auth-service:latest
          resources:
            limits:
              memory: "150Mi"
              cpu: "150m"
          ports:
            - containerPort: 8001
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: auth-service-secret
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  key: DB_HOSTNAME
                  name: auth-service-secret
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: DB_PORT
                  name: auth-service-secret
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: DB_DATABASE
                  name: auth-service-secret
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_PRIVATE_KEY
                  name: auth-service-secret
