apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: sudeepgowda55/auth-service:latest
          resources:
            limits:
              memory: "50Mi"
              cpu: "150m"
          ports:
            - containerPort: 8001
